language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  # TODO: Uncomment when JRuby will accept C extensions
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head

before_script:
  - ruby BuildExt.rb
